---
title: "Assignment #3"
author: "Huang Song Ren b04902099"
date: "2018/10/9"
output:
  html_document:
    df_print: paged
    highlight: textmate
    theme: spacelab
    toc: yes
---

#Problem 1
第一題：在Paid maternity leave的練習中，我們繪製了最後調查年代為level 5的兩張不同國家長條圖。請嘗試修改程式碼，畫出level 4的那兩張長條圖。
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
oldw <- getOption("warn")
options(warn = -1)
library(readxl)
options(stringsAsFactors = FALSE)
ldata <- read_excel("data/WORLD-MACHE_Gender_6.8.15.xls", "Sheet1", col_names=T)
matleave <- ldata[ , c(3, 6:24)]
matleave[is.na(matleave)] <- 0
m4 <- matleave[matleave$'matleave_13'==4, ]
m44 <- m4[m4$'matleave_95'==4,]
m04 <- m4[m4$'matleave_95'!=4,]

#plot m44
par(mfrow=c(4, 6), mai= c(0.2, 0.2, 0.2, 0.2))
for (i in 1:nrow(m44)){
    barplot(unlist(m44[i, -1]), border=NA, space=0,xaxt="n", yaxt="n", ylim = c(0,5))
	title(m44[i,1], line = -4, cex.main=3)
}
mtext("Plot m44", side = 1, cex = 2, outer=TRUE, line=-1)
#plot m04
par(mfrow=c(4, 6), mai= c(0.2, 0.2, 0.2, 0.2))
for (i in 1:nrow(m04)){
    barplot(unlist(m04[i, -1]), border=NA, space=0,xaxt="n", yaxt="n", ylim = c(0,5))
	title(m04[i,1], line = -4, cex.main=3)
}
mtext("Plot m04", side = 1, cex = 2, outer=TRUE, line=-1)
```

#Problem 2
第二題：下載或直接讀取空氣品質資料，並依照R02_3 read json ubike.Rmd 的方法繪製空氣品質地圖。上色應依照空氣品質監測網的上色方式。

```{r}
library(httr)
library(jsonlite)
url <- "https://taqm.epa.gov.tw/taqm/aqs.ashx?lang=tw&act=aqi-epa&ts=1538931940046"

origin <- fromJSON(content(GET(url), "text", encoding = "utf-8"))
air.df <- origin$Data
air.df <- air.df[air.df$AQI != "", ]
air.df$AQI <- sapply(air.df$AQI, strtoi)
air.df$lng <- as.numeric(air.df$lng)
air.df$lat <- as.numeric(air.df$lat)
air.df$AQI <- as.numeric(air.df$AQI)
```
```{r}
assignColor <- function(ratio){
  if(ratio >= 0 & ratio <= 50){
    return("#32CD31")
  }else if(ratio >= 51 & ratio <= 100){
    return("#FFFF00")
  }else if(ratio >= 101 & ratio <= 150){
    return("#FF8C00")
  }else if(ratio >= 151 & ratio <= 200){
    return("#FF0000")
  }else if(ratio >= 201 & ratio <= 300){
    return("#800080")
  }else if(ratio >= 301 & ratio <= 400){
    return("#8B4513")
  }else if(ratio >= 401 & ratio <= 500){
    return("#8B4513")
  }
}
assignshape <- function(ratio){
  if(ratio >= 0 & ratio <= 50){
    return(19)
  }else if(ratio >= 51 & ratio <= 100){
    return(15)
  }else if(ratio >= 101 & ratio <= 150){
    return(17)
  }else if(ratio >= 151 & ratio <= 200){
    return(10)
  }else if(ratio >= 201 & ratio <= 300){
    return(18)
  }else if(ratio >= 301 & ratio <= 400){
    return(11)
  }else if(ratio >= 401 & ratio <= 500){
    return(11)
  }
}
air.df$color <- sapply(air.df$AQI, assignColor)
air.df$shape <- sapply(air.df$AQI, assignshape)
# max(air.df$lat)
# min(air.df$lat)
# max(air.df$lng)
# min(air.df$lng)
```
```{r}
library(ggplot2)
library(ggmap)
ggmap(
	get_stamenmap(
		bbox=c(left = 118.312256, bottom = 21.758069, right = 122.092928, top = 26.153611),
		zoom=10,
		maptype='terrain'))+
  geom_point(data=air.df,
  		   aes(x=lng, y=lat),
  		   colour=air.df$color,
  		   shape=air.df$shape,
  		   size=air.df$AQI/20,
  		   alpha=0.4)
```

#Problem 3
第三題：讀取以下資料集中的任一個並轉成Data.frame（當然是json檔，不然csv編錯還得了）
違規藥品廣告資料(https://data.gov.tw/dataset/14196)

```{r}
library(httr)
library(jsonlite)
url <- "https://data.fda.gov.tw/opendata/exportDataList.do?method=ExportData&InfoId=156&logType=3"

origin <- fromJSON(content(GET(url), "text", encoding = "utf-8"))
origin.v <- unlist(origin)
origin.v <- origin.v[!is.na(origin.v)]
origin.m <- matrix(origin.v, byrow = TRUE, ncol = 10)
origin.df <- as.data.frame(origin.m)
names(origin.df) <- c('違規產品名稱', '違規廠商名稱或負責人', '處分機關', '處分日期', '處分法條', '違規情節', '刊播日期', '刊播媒體類別', '刊播媒體', '查處情形')
```
```{r}
origin.df
```
```{r}
options(warn = oldw)
```